[project]
name = "streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "babel>=2.17.0",
    "dotenv>=0.9.9",
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "streamlit>=1.51.0",
    "streamlit-tags>=1.2.8",
]
